ALTER TABLE user AUTO_INCREMENT = 1;
INSERT INTO user(passwd) VALUES("root");
INSERT INTO administrator VALUES(LAST_INSERT_ID(),"administrator");
INSERT INTO user(passwd) VALUES("test");
INSERT INTO purchaser VALUES(LAST_INSERT_ID(),"user1","男",0017);
INSERT INTO user(passwd) VALUES("test");
INSERT INTO seller VALUES(LAST_INSERT_ID(),"user2","简介简介简介简介简介","地址地址地址地址地址","菜菜菜菜菜菜",null);
ALTER TABLE user AUTO_INCREMENT = 100000;
ALTER TABLE orderOverview AUTO_INCREMENT = 10000;
ALTER TABLE Dish AUTO_INCREMENT = 10000;
INSERT INTO user(passwd) VALUES("KFC");
INSERT INTO seller VALUES(LAST_INSERT_ID(),"肯德基","Finger Lickin' Good","南区门口","全家桶",null);
INSERT INTO user(passwd) VALUES("xicha");
INSERT INTO seller VALUES(LAST_INSERT_ID(),"喜茶","喜悦发生","三号湾","多肉杨梅",null);